[tool.poetry]
name = "usefulltools"
version = "0.1.0"
description = ""
authors = ["LDS <vpfmzmtm@deepnoid.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
